spring:
  application:
    name: 'micro-users'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    allow-bean-definition-overriding: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
server:
  port: 8080
duration:
  time:
    cookie: 9000
    accessToken: 9000
time:
  token:
    refresh: 90080

