import startStrong from "../assets/images/startStrong.png";
import faerieFitText from "../assets/images/faerieFitText.png"
import endStrong from "../assets/images/endStrong.png";
import apple from "../assets/images/apple.png";
import telegram from "../assets/images/telegram.png";
import google from "../assets/images/google.png"
import home from "../assets/icons/home.svg"
import leef from "../assets/images/leef.png"
import calendar from "../assets/images/Calendar.png"
import cloacks from "../assets/images/Cloacks.png"
import notes from "../assets/images/Notes.png"
import fire from "../assets/images/fire.png"
import human from "../assets/images/human.png"
import mask from "../assets/images/mask.png"
import pill from "../assets/images/pill.png"
import love from "../assets/images/love.png"
import yt from "../assets/images/yt.png"
import human_love from "../assets/images/human_love.png"
import circle from "../assets/images/circle.png"
import cup from "../assets/images/cup.png"
export default {startStrong, faerieFitText, endStrong, apple, telegram, google, home, leef, cloacks, calendar, notes, fire, human, mask, pill, love, yt, human_love, circle, cup}